name: Build and deploy PrimeCare to Azure

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24.x'

      - name: Install dependencies
        working-directory: ./primecare-site-ready
        run: npm install

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: primecare-site
          path: ./primecare-site-ready

  deploy:
    runs-on: ubuntu-latest
    needs: build

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: primecare-site

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_2BD89E1F57AC419D8D458E4DF57A5B86 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_6FBAC0E7D9774987800CB2B433177043 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_891B0ABD605F4C70831F295E4E2D917A }}

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'udmsite'
          slot-name: 'Production'
          package: .
